name: Backend Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      PORT: ${{ secrets.PORT }}
      SECRET: ${{ secrets.SECRET }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Checkout directory
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Start PostgreSQL container
        run: |
          docker run --name postgres -d -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -p 5432:5432 postgres
          # Wait for PostgreSQL to be ready
          docker exec postgres sh -c 'while ! pg_isready -q -h localhost -p 5432 -U postgres; do sleep 1; done'

      - name: Run tests
        run: npm run test

      - name: Run lint with Prettier
        run: npm run prettier

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@v1
        with:
          args: deploy --remote-only

      - name: Stop PostgreSQL container
        run: docker stop postgres

  release_on_controller_changes:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'controllers/') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
