name: Deployment Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]
    
jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout directory
              uses: actions/checkout@v4
            
            - name: Set up Nodejs
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            - name: Initialize PostgreSQL container
              run: docker run -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 postgres

            - name: test
              run: npm run test

            - name: Trigger Deployment
              if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
              run: fly deploy